/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jedrick
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        c. createStoredProcedure("query_a",SQLEnum.STORED1);
         c. createStoredProcedure("query_b",SQLEnum.STORED1);
          c. createStoredProcedure("query_c",SQLEnum.STORED1);
 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Query1 = new javax.swing.JButton();
        Report = new javax.swing.JTextField();
        Query2 = new javax.swing.JButton();
        Country = new javax.swing.JTextField();
        Query3 = new javax.swing.JButton();
        Category = new javax.swing.JTextField();
        Query4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        Query5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Query1.setText("Query 1");
        Query1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query1ActionPerformed(evt);
            }
        });

        Report.setText("Sales Manager");

        Query2.setText("Query 2");
        Query2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query2ActionPerformed(evt);
            }
        });

        Country.setText("Japan");
        Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryActionPerformed(evt);
            }
        });

        Query3.setText("Query 3");
        Query3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query3ActionPerformed(evt);
            }
        });

        Category.setText("Seafood");

        Query4.setText("Query 4");
        Query4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query4ActionPerformed(evt);
            }
        });

        jTextField4.setText("jTextField1");

        Query5.setText("Query 5");

        jTextField5.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Report)
                        .addGap(18, 18, 18)
                        .addComponent(Query1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Query4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Query5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Country)
                            .addComponent(Category, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Query3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Query2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Query1)
                    .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Query2)
                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Query3)
                    .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Query4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Query5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        Report.getAccessibleContext().setAccessibleName("Report");
        Query2.getAccessibleContext().setAccessibleName("jButton2");
        Country.getAccessibleContext().setAccessibleName("Country");
        Query3.getAccessibleContext().setAccessibleName("jButton3");
        Category.getAccessibleContext().setAccessibleName("Category");
        Query4.getAccessibleContext().setAccessibleName("jButton4");
        Query5.getAccessibleContext().setAccessibleName("jButton5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryActionPerformed

    private void Query1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query1ActionPerformed
        System.out.println("++ORIGINAL++");
        c.issueQuery2("SELECT DISTINCT customerid\n" + "FROM orders\n" +
                        "WHERE employeeid IN (SELECT employeeid \n" +
                        "			      FROM employees\n" +
                        "			      WHERE reportsto = (SELECT employeeid\n" +
                        "       FROM employees\n" +
                        "       WHERE title = '" + Report.getText() + "'))"); 
        System.out.println("++OPTIMIZED++");
        c.issueQuery2("SELECT DISTINCT O.customerid\n" +
                        "FROM orders O,employees E\n" +
                        "WHERE O.employeeid = E.employeeid and\n" +
                        "	    E.reportsto = (SELECT employeeid\n" +
                        "     FROM employees\n" +
                        "     WHERE title = '" + Report.getText() + "')");
        System.out.println("++OPTSTORED++");
        c.issueQuery2("CALL query_a('" + Report.getText() + "')");
    }//GEN-LAST:event_Query1ActionPerformed

    private void Query2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query2ActionPerformed
        System.out.println("++ORIGINAL++");
        c.issueQuery2("	SELECT productname \n" +
                        "	FROM products\n" +
                        "	WHERE productid IN (SELECT productid\n" +
                        "				FROM products\n" +
                        "				WHERE supplierid IN (SELECT supplierid\n" +
                        "                                                   FROM suppliers\n" +
                        "                                                   WHERE country = '" + Country.getText() + "'));"); 
        System.out.println("++OPTIMIZED++");
        c.issueQuery2("        SELECT productname\n" +
                        "	FROM products\n" +
                        "	WHERE supplierid IN (SELECT supplierid\n" +
                        "                           FROM suppliers\n" +
                        "                           WHERE country = '" + Country.getText() + "');");
        System.out.println("++OPTSTORED++");
        c.issueQuery2("CALL query_b('" + Country.getText() + "')");
    }//GEN-LAST:event_Query2ActionPerformed

    private void Query3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query3ActionPerformed
        System.out.println("++ORIGINAL++");
        c.issueQuery2("SELECT companyname\n" +
                        "	FROM suppliers\n" +
                        "	WHERE supplierid IN (SELECT supplierid\n" +
                        "				    FROM products\n" +
                        "				    WHERE categoryid = (SELECT categoryid\n" +
                        "							    FROM categories\n" +
                        "							    WHERE categoryname = '" + Category.getText() + "'));"); 
        System.out.println("++OPTIMIZED++");
        c.issueQuery2("SELECT S.companyname\n" +
                        "FROM suppliers S, products P\n" +
                        "WHERE P.categoryid = (SELECT categoryid\n" +
                        "			FROM categories C\n" +
                        "                       WHERE C.categoryname = '" + Category.getText() + "')\n" +
                        "		        and S.supplierid = P.supplierid");
        System.out.println("++OPTSTORED++");
        c.issueQuery2("CALL query_c('" + Category.getText() + "')");
    }//GEN-LAST:event_Query3ActionPerformed

    private void Query4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query4ActionPerformed
       
    }//GEN-LAST:event_Query4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Category;
    private javax.swing.JTextField Country;
    private javax.swing.JButton Query1;
    private javax.swing.JButton Query2;
    private javax.swing.JButton Query3;
    private javax.swing.JButton Query4;
    private javax.swing.JButton Query5;
    private javax.swing.JTextField Report;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    Connector c = new Connector();
     
}
